import google.generativeai as genai
import streamlit as st
API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

def code_assistant(code: str) -> str:
    prompt = f"""find any error in the code and suggest corrected code if its correct display no error:{code}
    """
    
    response = model.generate_content(prompt)
    
  
    if response.text:
        return response.text
    else:
        return "⚠️ No response generated by Gemini."
    
    
    