import google.generativeai as genai
import streamlit as st
API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=API_KEY)
model = genai.GenerativeModel('gemini-2.5-flash')

def summarize_text(transcript: str) ->str :
    prompt = f"""Summarize text with the following structure:

    ### Key points
    [List all the key points from the text.]

    ### Corrections to be made
    [List all the mistakes and corrections made.]

    ### corrected text
    [Rewrite in correct form without any errors from the transcript: {transcript}]
    """
    
    response = model.generate_content(prompt)
    
    
    if response.text:
        return response.text
    else:
        return "⚠️ No response generated by Gemini."
